# Generated by Django 3.0.3 on 2020-02-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('carrer_title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
