# Generated by Django 3.0.3 on 2020-02-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_home', '0002_info_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
