# Generated by Django 3.0.3 on 2020-02-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_home', '0003_auto_20200221_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'Infos'},
        ),
        migrations.AlterModelTable(
            name='info',
            table=None,
        ),
    ]
